# Generated by Django 3.0.4 on 2020-03-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link_to_resource', models.FileField(upload_to='files/')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceType')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.User')),
            ],
        ),
    ]
