# Generated by Django 3.0.4 on 2020-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
